### ISSUE TITLE
compile error in main function

### ISSUE THREAD

**Issue by maoLB** [weblucas/mesh_based_mapping#1]
Hello,
I have met a compile while using catkin_make
The error are:
okvis_node.cpp: In function ‘int main(int, char**)’: error: ‘class okvis::ThreadedKFVio’ has no member named ‘setDenseCallback’
and okvis_node_synchronous.cpp: In function ‘int main(int, char**)’:error: ‘class okvis::ThreadedKFVio’ has no member named ‘setDenseCallback’
I double checked the file in project and found that there is no file about ThreadedKFVio.hpp in the path "/include/okvis". Can you upload this file in github?
Thanks.

**Comment by weblucas** [comment]
you probably download something wrong. My guess is that you didn't use the recursive.
just follow the four steps below that everything should work.

cd ~/catkin_ws/src
git clone --recursive https://github.com/weblucas/okvis_ros_mesh_mapping.git
cd ..
catkin build
